name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: todo_test
        ports: [ 5432:5432 ]
        options: >-
          --health-cmd "pg_isready -U postgres -d todo_test" --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7
        ports: [ 6379:6379 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done
      - name: Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/todo_test
          REDIS_URL: redis://localhost:6379/0
        run: |
          PYTHONPATH=. python -m pytest -q
